### ISSUE TITLE
BUG - creative_url_tag_history test failure

### ISSUE THREAD

**Issue by tac14yo** [fivetran/dbt_snapchat_ads_source#10]
**Are you a current Fivetran customer?** 

Tyler Schmidt, Data Scientist, Toggle/Farmers Insurance

**Describe the bug**

The unique_combination_of_columns test for stg_snapchat__creative_url_tag_history is giving a failure because of updated_at field not being included as part of the unique check despite being the ORDER BY for the is_most_recent_record

**Steps to reproduce**
1. Excute dbt test --select dbt_utils_unique_combination_of_columns_stg_snapchat__creative_url_tag_history_creative_id__param_key
2. See error

**Expected behavior**

I would exepct it to pass as the only reason for duplicate is updates to the information via the normal data flow (updated_at)

**Project variables configuration**

```yml
name: 'toggle_data_wh'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'toggle_data_wh'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  toggle_data_wh:
    +materialized: table
    staging:
      +materialized: view
  snapchat_ads_source:
    +schema: stg_ads

vars:
  snapchat_ads_source:
    snapchat_database: fnv_raw_db
    snapchat_schema: snapchat_ads 
```

**Package Version**

```yml
packages:

  - package: Datavault-UK/dbtvault
    version: 0.7.9
    
#  - package: fivetran/ad_reporting
#    version: 0.2.3

  - package: fivetran/snapchat_ads_source
    version: 0.3.0
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

This is not urgent as we turned off the test in production via --exclude .... and will not be updating our production run to DBT 1.0 for a bit so we will not be able to utlize any changes till after then anyway.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
